#!/bin/sh

SHIPVER=0.9.0
SHIPDIR=gtopo-${SHIPVER}
SHIPTAR=${SHIPDIR}.tar.gz

rm -rf ${SHIPDIR}
mkdir ${SHIPDIR}
cp *.h *.c ${SHIPDIR}
cp Makefile ${SHIPDIR}
cp README ${SHIPDIR}
cp COPYING ${SHIPDIR}
cp INSTALL ${SHIPDIR}
cp Chanelog ${SHIPDIR}
cp TODO ${SHIPDIR}
tar czvf ${SHIPTAR} ${SHIPDIR}

cp ${SHIPTAR} /www/cholla/gtopo
