#!/bin/sh

# As of 6-28-2020 I don't support this
# anyone who wants the sources should
# obtain them from github.
exit

SHIPVER=`cat VERSION`
SHIPDIR=gtopo-${SHIPVER}
SHIPTAR=${SHIPDIR}.tar.gz

rm -rf ${SHIPDIR}
mkdir ${SHIPDIR}
# cp *.h *.c ${SHIPDIR}
# cp Makefile ${SHIPDIR}
cp -var src ${SHIPDIR}
cp README ${SHIPDIR}
cp COPYING ${SHIPDIR}
cp INSTALL ${SHIPDIR}
cp VERSION ${SHIPDIR}
cp ChangeLog ${SHIPDIR}
cp TODO ${SHIPDIR}
tar czvf ${SHIPTAR} ${SHIPDIR}
rm -rf ${SHIPDIR}

#cp ${SHIPTAR} /www/cholla/gtopo/downloads
#cp TODO /www/cholla/gtopo/TODO.txt

scp ${SHIPTAR} cholla:/u1/www/gtopo/downloads
scp TODO cholla:/u1/www/gtopo/TODO.txt

rm ${SHIPTAR}
